### ISSUE TITLE
Ion mobility filtering for PIF calculation (PIF.py)

### ISSUE THREAD

**Issue by ATomioka** [jcharkow/imMQExplorer#1]
Hello! 

I enjoyed reading your article! Good work!
By the way, I am now trying to use imMQExplorer to calculate PIF on timsTOF data.
I noticed that the IM information filtering was done twice in the isolation window intensity extraction process, why did you filter the peaks twice (MQ IM filtering, then raw data IM filtering)? I wonder if it is enough to filter out the peaks once based on the IM information from the raw data (.tdf).

Best regards,

**Comment by jcharkow** [comment]
Hi,

Thank you for your interest interest in this work. Can you please be more specific to what section you are referring to? Is this in the pif.py script?

**Comment by ATomioka** [comment]
Hi,

Yes, I mention lines 218 and 224 in the pif.py script.

**Comment by jcharkow** [comment]
Line 218 I am filtering the IM boundaries based on what MQ detected in its feature detection tool.

Line 224 I am filtering the peaks based on the raw data MS2 windows. These boundaries are not based on the actual feature but rather a fixed isolation window around the precursor the instrument is isolating.

There are some edge cases where instrument selected range is not a complete subset of the MQ detected scans range (MQ detected range is smaller than the instrument precursor range). For these cases in order to be stringent with the PIF calculations, I filter on both IM ranges because I know that not all of the IM isolated from the raw data are corresponding with the feature of interest. 

In practice filtering just on the instrument level would likely lead to very similar results as these cases are not common.
Furthermore, the MQ analysis results I used were from the original 2015 paper so I am not sure if there are further updates to their feature detection algorithm that this is not a problem anymore.
